config/routes.rb
Rails.application.routes.draw do
  resources :sudos
  get 'configuration_detail_types/format_configure_type'
  get 'configuration_templates/versions'
  resources :configuration_detail_types
  resources :configuration_details
  resources :configuration_files
  resources :configuration_templates
  resources :catalog_items
  resources :object_types
  resources :blueprint_objects
  resources :blueprints
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/landing'
  get 'welcome/main'
  authenticated do
    root :to => 'welcome#main'
  end

  root 'welcome#landing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blueprint.rb
class Blueprint < ApplicationRecord
  belongs_to :user
  has_many :blueprint_objects
  accepts_nested_attributes_for :blueprint_objects, allow_destroy: true

end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  before_action :set_blueprint, only: [:show, :edit, :update, :destroy]

  # GET /blueprints
  # GET /blueprints.json
  def index
    @blueprints = Blueprint.all
    respond_to do |format|
      format.html
      format.json {
        blueprints=Blueprint.all
        .where("name LIKE ?", "%#{params[:name]}%")
        .where("description LIKE ?", "%#{params[:description]}%").includes(:blueprint_objects)
        data=[]
        blueprints.each do |bp|
          d={
            :name => bp.name,
            :description => bp.description,
            :id => bp.id,
            :version => bp.version,
            :group => bp.group,
            :user => bp.user.full_name,
            :blueprint_objects => bp.blueprint_objects
          }
          data  <<d

        end
        render json: {'value' => data}
      }
      #.where("name LIKE ?", "%#{params[:name]}%")
    end
  end

  # GET /blueprints/1
  # GET /blueprints/1.json
  def show
  end

  # GET /blueprints/new
  def new
    @blueprint = Blueprint.new
  end

  # GET /blueprints/1/edit
  def edit
  end

  # POST /blueprints
  # POST /blueprints.json
  def create
    if params[:name].blank?
      @blueprint = Blueprint.new(blueprint_params)

    else
      @blueprint = Blueprint.new(name: params[:name], description: params[:description])

    end
    @blueprint.user=current_user
    respond_to do |format|
      if @blueprint.save
        format.html { redirect_to @blueprint, notice: 'Blueprint was successfully created.' }
        format.json { render json: @blueprint }
      else
        puts  @blueprint.errors.inspect
        format.html { render :new }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blueprints/1
  # PATCH/PUT /blueprints/1.json
  def update
    if params[:name].blank?
      updated=@blueprint.update(blueprint_params)
    else
      updated=@blueprint.update(name: params[:name], description: params[:description])
    end
    respond_to do |format|
      if updated
        format.html { redirect_to @blueprint, notice: 'Blueprint was successfully updated.' }
        format.json { render json: @blueprint         }
      else
        puts @blueprint.errors.inspect
        format.html { render :edit }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blueprints/1
  # DELETE /blueprints/1.json
  def destroy
    @blueprint.destroy
    respond_to do |format|
      format.html { redirect_to blueprints_url, notice: 'Blueprint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blueprint
    @blueprint = Blueprint.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blueprint_params
    params.require(:blueprint).permit(:name, :description, :version, :user_id, :group, blueprint_objects_attributes: [:id, :configuration_template_id,:configuration_file_id, :object_type_id, :catalog_item_id, :blueprint_id, :name, :description,  :_destroy,:version])
  end
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/views/blueprints/_blueprint_object_fields.html.erb
<div class="nested-fields">
  <div class="col-md-3">


  <div class="panel panel-success">
    <div class="panel-body">
  <%= f.association :object_type,:include_blank => false %>
  <%= f.association :catalog_item,:include_blank => false %>
  <%= f.association :configuration_template,:include_blank => false,  input_html: { data: {remote: :true, url: "/configuration_templates/versions"} } %>
<%if  f.object.configuration_template.blank?%>
<%= f.association :configuration_file ,:include_blank => false %>

<%else%>
  <%= f.association :configuration_file,collection: f.object.configuration_template.configuration_files ,label_method: :version,:include_blank => false %>
<%end%>
  <%= f.input :name %>

    <%= f.input :description %>
    <%= link_to_remove_association "remove object", f %>
  </div>
</div>
</div>
</div>

app/views/blueprints/_form.html.erb
<%= simple_form_for(@blueprint) do |f| %>
<div class="container">
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%# f.input :version %>
    <%# f.association :user,:include_blank => false, :label_method => :full_name %>
    <%# f.input :group %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Save Blueprint" %>
    <%= link_to_add_association 'add object', f, :blueprint_objects, "data-association-insertion-method" => :append, :class => "btn btn-default" %>
<hr>
  </div>





  <div   id="blueprint_objects">
  <%= f.simple_fields_for :blueprint_objects do |blueprint_object| %>

    <%= render 'blueprint_object_fields', f: blueprint_object %>

  <% end %>
</div>
<hr>

<% end %>
</div>

app/views/blueprints/edit.html.erb
<h1>Editing Blueprint</h1>

<%= render 'form', blueprint: @blueprint %>

<%= link_to 'Show', @blueprint %> |
<%= link_to 'Back', blueprints_path %>

app/views/blueprints/index.html.erb
<%
extra_opt='
filtering: false,
inserting: true,
editing: false,
removing: false,

fields: [
{ name: "id", type: "text", itemTemplate: function(value) {
                            var output= $("<a>").attr("href", "blueprints/"+value).text("View")
                            output.append("/")
                            output.append($("<a>").attr("href", "blueprints/"+value+"/edit").text("Edit"));
                            return output;
                        } , width: 200, filtering: false,width: 50,title: "View", editing: false
  },
{ name: "name", type: "text",title: "Blueprint" },
{ name: "description", type: "text",title: "Description" },
{ name: "blueprint_objects", width: 200, filtering: false, title: "Objects",
  itemTemplate: function(value) {
    if (value) {
  var $info=$("<div>").addClass("client-info")
  for (var i = 0; i < value.length; i++) {
    $info.append($("<p>").text(value[i].name));
  }
    for (var blueprint_object  in value) {
  }
  return $("<tr>").append($("<td>").append($info));
  }
}
  },
{ name: "version", type: "number",filtering: false, title: "Version",editing: false,inserting: false, },
{ name: "user", type: "text",filtering: false,title: "User",editing: false,inserting: false, },
{ type: "control",deleteButton: true,editButton: false }

]'
%>
<%= render 'partials/grid', :ajax_url => "blueprints",:extra_opt => extra_opt  %>

app/views/blueprints/new.html.erb
<h1>New Blueprint</h1>

<%= render 'form', blueprint: @blueprint %>

<%= link_to 'Back', blueprints_path %>

app/views/blueprints/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="list-group">
  <li class="list-group-item  ">
    <p>
      <strong>Blueprint Name:</strong>
      <%= @blueprint.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @blueprint.description %>
    </p>

    <p>
      <strong>Version:</strong>
      <%= @blueprint.version %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @blueprint.user.full_name %>
    </p>

    <p>
      <strong>Group:</strong>
      <%= @blueprint.group %>
    </p>
</li>
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>catalog_item</th>
      <th>Name</th>
      <th>Description</th>
      <th>Configure template</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
  <%@blueprint.blueprint_objects.each  do |bo| %>

<%=raw "<tr><td> #{bo.object_type.name} </td><td> #{bo.catalog_item.name} </td><td> #{bo.name} </td><td> #{bo.description} </td>
<td> #{bo.configuration_template.name} </td><td> #{bo.configuration_file.version} </td>

</tr>"%>


<%end%>
</tbody>
</table>
</ul>


<%= link_to 'Edit', edit_blueprint_path(@blueprint) %> |
<%= link_to 'Back', blueprints_path %>