config/routes.rb
Rails.application.routes.draw do
  resources :sudos
  get 'configuration_detail_types/format_configure_type'
  get 'configuration_templates/versions'
  resources :configuration_detail_types
  resources :configuration_details
  resources :configuration_files
  resources :configuration_templates
  resources :catalog_items
  resources :object_types
  resources :blueprint_objects
  resources :blueprints
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/landing'
  get 'welcome/main'
  authenticated do
    root :to => 'welcome#main'
  end

  root 'welcome#landing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/configuration_detail.rb
class ConfigurationDetail < ApplicationRecord
  belongs_to :configuration_template
  belongs_to :configuration_detail_type
end

app/models/configuration_detail_type.rb
class ConfigurationDetailType < ApplicationRecord
has_many :configuration_detail_data
end

app/controllers/configuration_details_controller.rb
class ConfigurationDetailsController < ApplicationController
  before_action :set_configuration_detail, only: [:show, :edit, :update, :destroy]

  # GET /configuration_details
  # GET /configuration_details.json
  def index
    @configuration_details = ConfigurationDetail.all
  end

  # GET /configuration_details/1
  # GET /configuration_details/1.json
  def show
  end

  # GET /configuration_details/new
  def new
    @configuration_detail = ConfigurationDetail.new
  end

  # GET /configuration_details/1/edit
  def edit
  end

  # POST /configuration_details
  # POST /configuration_details.json
  def create
    @configuration_detail = ConfigurationDetail.new(configuration_detail_params)

    respond_to do |format|
      if @configuration_detail.save
        format.html { redirect_to @configuration_detail, notice: 'Configuration detail was successfully created.' }
        format.json { render :show, status: :created, location: @configuration_detail }
      else
        format.html { render :new }
        format.json { render json: @configuration_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configuration_details/1
  # PATCH/PUT /configuration_details/1.json
  def update
    respond_to do |format|
      if @configuration_detail.update(configuration_detail_params)
        format.html { redirect_to @configuration_detail, notice: 'Configuration detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @configuration_detail }
      else
        format.html { render :edit }
        format.json { render json: @configuration_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configuration_details/1
  # DELETE /configuration_details/1.json
  def destroy
    @configuration_detail.destroy
    respond_to do |format|
      format.html { redirect_to configuration_details_url, notice: 'Configuration detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuration_detail
      @configuration_detail = ConfigurationDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def configuration_detail_params
      params.require(:configuration_detail).permit(:configuration_template_id, :configuration_detail_type_id, :configuration_detail_order, :configuration_detail_data)
    end
end

app/helpers/configuration_details_helper.rb
module ConfigurationDetailsHelper
end

app/views/configuration_details/_form.html.erb
<%= simple_form_for(@configuration_detail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :configuration_template %>
    <%= f.association :configuration_detail_type %>
    <%= f.input :configuration_detail_order %>
    <%= f.input :configuration_detail_data %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/configuration_details/edit.html.erb
<h1>Editing Configuration Detail</h1>

<%= render 'form', configuration_detail: @configuration_detail %>

<%= link_to 'Show', @configuration_detail %> |
<%= link_to 'Back', configuration_details_path %>

app/views/configuration_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Configuration Details</h1>

<table>
  <thead>
    <tr>
      <th>Configuration template</th>
      <th>Configuration detail type</th>
      <th>Configuration detail order</th>
      <th>Configuration detail data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configuration_details.each do |configuration_detail| %>
      <tr>
        <td><%= configuration_detail.configuration_template %></td>
        <td><%= configuration_detail.configuration_detail_type %></td>
        <td><%= configuration_detail.configuration_detail_order %></td>
        <td><%= configuration_detail.configuration_detail_data %></td>
        <td><%= link_to 'Show', configuration_detail %></td>
        <td><%= link_to 'Edit', edit_configuration_detail_path(configuration_detail) %></td>
        <td><%= link_to 'Destroy', configuration_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration Detail', new_configuration_detail_path %>

app/views/configuration_details/new.html.erb
<h1>New Configuration Detail</h1>

<%= render 'form', configuration_detail: @configuration_detail %>

<%= link_to 'Back', configuration_details_path %>

app/views/configuration_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Configuration template:</strong>
  <%= @configuration_detail.configuration_template %>
</p>

<p>
  <strong>Configuration detail type:</strong>
  <%= @configuration_detail.configuration_detail_type %>
</p>

<p>
  <strong>Configuration detail order:</strong>
  <%= @configuration_detail.configuration_detail_order %>
</p>

<p>
  <strong>Configuration detail data:</strong>
  <%= @configuration_detail.configuration_detail_data %>
</p>

<%= link_to 'Edit', edit_configuration_detail_path(@configuration_detail) %> |
<%= link_to 'Back', configuration_details_path %>