config/routes.rb
Rails.application.routes.draw do
  resources :sudos
  get 'configuration_detail_types/format_configure_type'
  get 'configuration_templates/versions'
  resources :configuration_detail_types
  resources :configuration_details
  resources :configuration_files
  resources :configuration_templates
  resources :catalog_items
  resources :object_types
  resources :blueprint_objects
  resources :blueprints
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/landing'
  get 'welcome/main'
  authenticated do
    root :to => 'welcome#main'
  end

  root 'welcome#landing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/configuration_file.rb
class ConfigurationFile < ApplicationRecord
  belongs_to :configuration_template
end

app/controllers/configuration_files_controller.rb
class ConfigurationFilesController < ApplicationController
  before_action :set_configuration_file, only: [:show, :edit, :update, :destroy]

  # GET /configuration_files
  # GET /configuration_files.json
  def index
    @configuration_files = ConfigurationFile.all
  end

  # GET /configuration_files/1
  # GET /configuration_files/1.json
  def show
    puts @configuration_file.file_content
  end

  # GET /configuration_files/new
  def new
    @configuration_file = ConfigurationFile.new
  end

  # GET /configuration_files/1/edit
  def edit
  end

  # POST /configuration_files
  # POST /configuration_files.json
  def create
    @configuration_file = ConfigurationFile.new(configuration_file_params)

    respond_to do |format|
      if @configuration_file.save
        format.html { redirect_to @configuration_file, notice: 'Configuration file was successfully created.' }
        format.json { render :show, status: :created, location: @configuration_file }
      else
        format.html { render :new }
        format.json { render json: @configuration_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configuration_files/1
  # PATCH/PUT /configuration_files/1.json
  def update
    respond_to do |format|
      if @configuration_file.update(configuration_file_params)
        format.html { redirect_to @configuration_file, notice: 'Configuration file was successfully updated.' }
        format.json { render :show, status: :ok, location: @configuration_file }
      else
        format.html { render :edit }
        format.json { render json: @configuration_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configuration_files/1
  # DELETE /configuration_files/1.json
  def destroy
    @configuration_file.destroy
    respond_to do |format|
      format.html { redirect_to configuration_files_url, notice: 'Configuration file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuration_file
      @configuration_file = ConfigurationFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def configuration_file_params
      params.require(:configuration_file).permit(:configuration_template_id, :version, :file_content)
    end
end

app/helpers/configuration_files_helper.rb
module ConfigurationFilesHelper
end

app/views/configuration_files/_form.html.erb
<%= simple_form_for(@configuration_file) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :configuration_template %>
    <%= f.input :version %>
    <%= f.input :file_content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/configuration_files/edit.html.erb
<h1>Editing Configuration File</h1>

<%= render 'form', configuration_file: @configuration_file %>

<%= link_to 'Show', @configuration_file %> |
<%= link_to 'Back', configuration_files_path %>

app/views/configuration_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Configuration Files</h1>

<table>
  <thead>
    <tr>
      <th>Configuration template</th>
      <th>Version</th>
      <th>File content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configuration_files.each do |configuration_file| %>
      <tr>
        <td><%= configuration_file.configuration_template %></td>
        <td><%= configuration_file.version %></td>
        <td><%= configuration_file.file_content %></td>
        <td><%= link_to 'Show', configuration_file %></td>
        <td><%= link_to 'Edit', edit_configuration_file_path(configuration_file) %></td>
        <td><%= link_to 'Destroy', configuration_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration File', new_configuration_file_path %>

app/views/configuration_files/new.html.erb
<h1>New Configuration File</h1>

<%= render 'form', configuration_file: @configuration_file %>

<%= link_to 'Back', configuration_files_path %>

app/views/configuration_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Configuration template:</strong>
  <%= @configuration_file.configuration_template %>
</p>

<p>
  <strong>Version:</strong>
  <%= @configuration_file.version %>
</p>

<p>
  <strong>File content:</strong>
  <%= @configuration_file.file_content %>
</p>

<%= link_to 'Edit', edit_configuration_file_path(@configuration_file) %> |
<%= link_to 'Back', configuration_files_path %>

app/views/configuration_files/show.js.erb
$('#modal_file_content').modal('toggle');
$('#file_content').html('<%=j @configuration_file.file_content%>');