config/routes.rb
Rails.application.routes.draw do
  resources :sudos
  get 'configuration_detail_types/format_configure_type'
  get 'configuration_templates/versions'
  resources :configuration_detail_types
  resources :configuration_details
  resources :configuration_files
  resources :configuration_templates
  resources :catalog_items
  resources :object_types
  resources :blueprint_objects
  resources :blueprints
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/landing'
  get 'welcome/main'
  authenticated do
    root :to => 'welcome#main'
  end

  root 'welcome#landing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blueprint.rb
class Blueprint < ApplicationRecord
  belongs_to :user
  has_many :blueprint_objects
  accepts_nested_attributes_for :blueprint_objects, allow_destroy: true

end

app/models/blueprint_object.rb
class BlueprintObject < ApplicationRecord
  belongs_to :object_type
  belongs_to :catalog_item
  belongs_to :blueprint
  belongs_to :configuration_template
  belongs_to :configuration_file
end

app/models/catalog_item.rb
class CatalogItem < ApplicationRecord
end

app/models/configuration_detail.rb
class ConfigurationDetail < ApplicationRecord
  belongs_to :configuration_template
  belongs_to :configuration_detail_type
end

app/models/configuration_detail_type.rb
class ConfigurationDetailType < ApplicationRecord
has_many :configuration_detail_data
end

app/models/configuration_file.rb
class ConfigurationFile < ApplicationRecord
  belongs_to :configuration_template
end

app/models/configuration_template.rb
class ConfigurationTemplate < ApplicationRecord
  has_many :configuration_details, :dependent => :destroy
  has_many :configuration_files, :dependent => :destroy
  accepts_nested_attributes_for :configuration_details, allow_destroy: true
  after_save :create_yaml
  attr_accessor :version
  def version
    self.configuration_files.order('version DESC').limit(1).first.version
  end
  def create_yaml
    puts "checking if Configure has changed"
    output=[]
    self.configuration_details.each do |data|
      output <<"#{data.configuration_detail_order}:#{data.configuration_detail_type.name}:#{data.configuration_detail_data}\n"
    end
    current_yaml=output.sort!.join
    version=0
    latest=self.configuration_files.order('version DESC').limit(1).first
    if latest.blank?
      version=1
      puts "******************************not file existing , need to create"


    else
      if current_yaml  != latest.file_content
        puts "current:#{current_yaml}"
        puts "existin:#{latest.file_content}"
        version=latest.version+1
      end
    end
    if version >0
      configuration_file=ConfigurationFile.new
      configuration_file.file_content=current_yaml
      configuration_file.version=version
      configuration_file.configuration_template_id=self.id
      configuration_file.save
      puts "******************************Creating new file version #{configuration_file}"
    else
      puts "******************************content did not  change"

    end

  end
end

app/models/object_type.rb
class ObjectType < ApplicationRecord
end

app/models/sudo.rb
class Sudo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :full_name

  def full_name
    return "#{self.last_name} #{self.first_name}"
  end


end

app/controllers/sudos_controller.rb
class SudosController < ApplicationController
  before_action :set_sudo, only: [:show, :edit, :update, :destroy]

  # GET /sudos
  # GET /sudos.json
  def index
    respond_to do |format|
      format.html
      format.json {
        data=Sudo.all
        .where("name LIKE ?", "%#{params[:name]}%")
        .where("description LIKE ?", "%#{params[:description]}%")
        .where("sudo_rule LIKE ?", "%#{params[:sudo_rule]}%")
        render json: {'value' => data}
      }
      #.where("name LIKE ?", "%#{params[:name]}%")
    end
  end
  def create
    data = Sudo.new(name: params[:name], description: params[:description],sudo_rule: params[:sudo_rule])
    if data.save
    render json: data
    end
  end

  # PATCH/PUT /configuration_detail_types/1
  # PATCH/PUT /configuration_detail_types/1.json
  def update
    respond_to do |format|
      if @sudo.update(name: params[:name], description: params[:description],sudo_rule: params[:sudo_rule])
        format.json { render json: @sudo }
      end
    end
  end

  # DELETE /configuration_detail_types/1
  # DELETE /configuration_detail_types/1.json
  def destroy
    if @sudo.destroy
      head :ok
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sudo
      @sudo = Sudo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sudo_params
      params.require(:sudo).permit(:name, :description, :sudo_rule)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def landing
  end
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blueprint_objects_helper.rb
module BlueprintObjectsHelper
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/helpers/catalog_items_helper.rb
module CatalogItemsHelper
end

app/helpers/object_types_helper.rb
module ObjectTypesHelper
end

app/helpers/sudos_helper.rb
module SudosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="col-md-12"><hr></div>
<footer class="footer">
  <div class="container">
    <p class="text-muted"> </p>

  </div>
</footer>

app/views/layouts/_top_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">gfrrg</span>
        <span class="icon-bar">fgfg</span>
        <span class="icon-bar">cccc</span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Automaton</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-ex-collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <li >
          <a href="<%=blueprints_path%>">Blueprints</a>
        </li>
        <li>
          <a href="#">Instances</a>
        </li>
        <li>
          <a href="<%=configuration_templates_path%>">Configuration template</a>
        </li>
        <%= render 'layouts/top_nav_advance' %>


        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.full_name%> <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to('Edit profile', edit_user_registration_path) %>

    </li>

    <li role="separator" class="divider"></li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
  </ul>
</li>

        <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_top_nav_advance.html.erb

        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Advance <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <li><%= link_to "Configuration types", configuration_detail_types_path %></li>
      <li><%= link_to "Object types", object_types_path %></li>
      <li><%= link_to "Catalogs", catalog_items_path %></li>

    </li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Automaton</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style type="text/css">
   body { background: #f9f2ec !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

</head>

<body>

    <%= render 'layouts/top_nav' %>
    <div class="container">
        <pre>home -> <%=controller_name%> 
      </pre>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Automaton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cover">

        <div class="cover-image" style="background-image: url(/assets/bg_penguin.jpg);"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-4 col-centered">
    <%= yield %>
  </div>


</div>

</div>
</div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Automaton</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="cover">
    <%= render 'layouts/top_nav' %>

    <%= yield %>
  </div>

</body>
</html>

app/views/partials/_grid.html.erb
<div id="jsGrid"></div>

<script>
$(function() {

  $("#jsGrid").jsGrid({
    height: "auto",
    width: "100%",


    sorting: true,
    paging: true,
    autoload: true,
    pageSize: 10,
    filtering: true,
    deleteConfirm: function(item) {
      return item.name + " will be removed. Are you sure?";
    },

    controller: {
      loadData: function(filter) {
        var d = $.Deferred();

        $.ajax({
          url: "<%=ajax_url%>",
          dataType: "json",
          data: filter,
        }).done(function(response) {
          d.resolve(response.value);
        });

        return d.promise();
      },
      insertItem: function(item) {
        return $.ajax({
          type: "POST",
          dataType: "json",
          url: "<%=ajax_url%>",
          data: item
        });
      },
      updateItem: function(item) {
        return $.ajax({
          type: "PUT",
          dataType: "json",
          url: "<%=ajax_url%>/" + item.id,
          data: item
        });
      },

      deleteItem: function(item) {
        return $.ajax({
          type: "DELETE",
          url: "<%=ajax_url%>/" + item.id
        });
      },


    },

      <%if defined?  extra_opt%>
      <%=raw extra_opt%>
      <%else%>
      filtering: true,
      inserting: true,
      editing: true,
          fields: [
      { name: "name", type: "text", title: "Name" },
      { name: "description", type: "text",title: "Description" },
      { type: "control" }
    ]
    <%end%>


  });

});
</script>